AppBundle\Entity\History:
    type: entity
    table: history
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        content:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        image:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        resourceid:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: resourceId
        createdAt:
            type: datetime
            nullable: true
            column: created_at
    lifecycleCallbacks: {  }
